on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        run:  | 
          /usr/local/bin/r $GITHUB_WORKSPACE/workflows/defaultV2/combined_workflow.R
